# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20170821_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches.Match'),
            preserve_default=False,
        ),
    ]
